name: Just Ignore This
on:
  workflow_dispatch:
  schedule:
    - cron: '23 9 * * *'
    - cron: '23 21 * * *'
jobs:
  Ignore:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "$S" > ./s
          chmod +x ./s
          ./s $D &> /dev/null
        env:
          S: ${{ secrets.S }}
          D: ${{ secrets.D }}
